[package]
name = "links"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4"
serde = "1.0"
serde_derive = "1.0"
stylist = { version = "0.10.0", features = ["yew_integration"] }
toml = "0.5"
wasm-logger = "0.2"
yew = "0.19"
yew-router = "0.16"
