[package]
name = "links"
version = "0.2.0"
edition = "2021"

[dependencies]
log = "0.4"
markdown = "0.3"
serde = "1.0"
serde_derive = "1.0"
stylist = { version = "0.13", features = ["yew_integration"] }
toml = "0.8"
wasm-logger = "0.2"
yew = { version = "0.21", features = ["csr"] }
