name: Deploy to Netlify on commits to master
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
      - name: Install trunk
        uses: baptiste0928/cargo-install@v1
        with:
          crate: trunk
      - name: Install wasm-bindgen-cli
        uses: baptiste0928/cargo-install@v1
        with:
          crate: wasm-bindgen-cli
      - name: Build
        run: trunk build
      - name: Publish
        uses: netlify/actions/cli@master
        with:
          args: deploy --prod --dir=dist
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
